FROM ubuntu:18.04

RUN apt-get install golang &&\
go get github.com/boltdb/bolt &&\
go get github.com/go-sql-driver/mysql &&\
go get github.com/unrolled/render &&\
go get github.com/gorilla/mux &&\
go get github.com/codegangsta/negroni
